# Generated by Django 4.1.5 on 2023-01-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('hp', models.CharField(blank=True, max_length=13, null=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('jenis_sekolah', models.CharField(choices=[('SMK', 'Sekolah Menengah Kejuruan'), ('Universitas', 'Universitas')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sekolah',
                'db_table': 'sekolah',
                'ordering': ['-id'],
            },
        ),
    ]
