# Generated by Django 4.1.5 on 2023-01-18 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasekolah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasekolah',
            name='jenis_sekolah',
        ),
        migrations.RemoveField(
            model_name='datasekolah',
            name='web',
        ),
        migrations.AddField(
            model_name='datasekolah',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sekolah_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasekolah',
            name='kabupaten_kota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datasekolah',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datasekolah',
            name='npsn',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datasekolah',
            name='provinsi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datasekolah',
            name='status',
            field=models.CharField(choices=[('Swasta', 'Swasta'), ('Negeri', 'Negeri')], default='Swasta', max_length=10),
        ),
    ]
