# Generated by Django 4.1.5 on 2023-01-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datasekolah',
            new_name='Datasiswa',
        ),
    ]
