# Generated by Django 4.1.5 on 2023-01-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataperusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('hp', models.CharField(blank=True, max_length=13, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('jenis_perusahaan', models.CharField(choices=[('PT', 'Perseroan Terbatas'), ('CV', 'Commanditaire Vennootschap'), ('Koperasi', 'Koperasi'), ('Firma', 'Firma'), ('Persero', 'Persero'), ('Perseorangan', 'Perseorangan')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Perusahaan',
                'db_table': 'perusahaan',
                'ordering': ['-id'],
            },
        ),
    ]
